# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aixianfeng', '0006_foodtypes_goods_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='trackid',
            new_name='pd',
        ),
    ]
